apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wolvox-prod
bases:
- ../../base

patches:
- path: replicas-patch.yaml
- path: resource-patch.yaml

configMapGenerator:
- name: wolvox-config
  behavior: merge
  literals:
  - LOG_LEVEL=INFO 